# Generated by Django 5.0.3 on 2024-04-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
